# Generated by Django 2.2.7 on 2019-11-23 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('metin', models.TextField()),
                ('olusturma_tarihi', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
